export const countriesActionTypes = {
  FETCH_COUNTRIES_CASES_START: 'FETCH_COUNTRIES_CASES_START',
  FETCH_COUNTRIES_CASES_SUCCESS: 'FETCH_COUNTRIES_CASES_SUCCESS',
  FETCH_COUNTRIES_CASES_FAIL: 'FETCH_COUNTRIES_CASES_FAIL',

  FETCH_COUNTRY_START: 'FETCH_COUNTRY_START',
  FETCH_COUNTRY_SUCCESS: 'FETCH_COUNTRY_SUCCESS',
  FETCH_COUNTRY_FAIL: 'FETCH_COUNTRY_FAIL'
};